

typedef enum error_type {
    INVALID_COMMAND,
    INVALID_MAT,
    MISSING_MAT,
    ILLEGAL_NUMBER,
    MISSING_NUMBER,
    ILLEGAL_ENDING,
    MULTIPLE_COMMAS,
    MISSING_COMMA,
    ILLEGAL_COMMA,
    MISSING_WHITE,
    ILLEGAL_CHAR,
    ILLEGAL_LINE_LEN,
    ILLEGAL_EXIT,
    NULL_ARGUMENT,
    NO_ERROR
} Error;